from typing import Protocol, Sequence, TypeVar

from fealpy.backend import TensorLike

class ABCPDEDataProtocol(Protocol):
    def geo_dimension(self) -> int: ...
    def domain(self) -> Sequence[float]: ...
    def solution(self, p: TensorLike) -> TensorLike: ...
    def gradient(self, p: TensorLike) -> TensorLike: ...
    def source(self, p: TensorLike) -> TensorLike: ...
    def dirichlet(self, p: TensorLike) -> TensorLike: ...
    def is_dirichlet_boundary(self, p: TensorLike) -> TensorLike: ...

ABCPDEDataT = TypeVar("ABCPDEDataT", bound=ABCPDEDataProtocol)

DATA_TABLE = {
    # example name: (file_name, class_name)
    "sin": ("sin_data_1d", "SinData1D"),
    "sinsin": ("sin_sin_data_2d", "SinSinData2D"),
    "sincos": ("sin_cos_data_3d", "SinCosData3D"),

}