from typing import Protocol, Sequence, TypeVar

from fealpy.backend import TensorLike
from fealpy.mesh.mesh_base import Mesh


class OPCPDEDataProtocol(Protocol):
    description : str
    def geo_dimension(self) -> int: ...
    def domain(self) -> Sequence[float]: ...
    def diffusion_coef(self, p: TensorLike) -> TensorLike: ...
    def advection_coef(self, p: TensorLike) -> TensorLike: ...
    def reaction_coef(self, p: TensorLike) -> TensorLike: ...
    def solution(self, p: TensorLike) -> TensorLike: ...
    def gradient(self, p: TensorLike) -> TensorLike: ...
    def flux(self, p: TensorLike) -> TensorLike: ...
    def source(self, p: TensorLike) -> TensorLike: ...
    def dirichlet(self, p: TensorLike) -> TensorLike: ...
    def init_mesh(self) -> Mesh: ...
    def A_matrix(self, p: TensorLike) -> TensorLike: ...
    def A_inverse(self, p: TensorLike) -> TensorLike: ...
    def pd_fun(self, p: TensorLike) -> TensorLike: ...
    def y_d_fun(self, p: TensorLike) -> TensorLike: ...
    def div_pd_fun(self, p: TensorLike) -> TensorLike: ...
    def grad_dirichlet(self, p: TensorLike) -> TensorLike: ...
    def f_u(self, p: TensorLike, u: TensorLike, index: int = None) -> TensorLike: ...
    def f_fun(self, p: TensorLike, index: int = None) -> TensorLike: ...
    def p_solution(self, p: TensorLike) -> TensorLike: ...
    def q_solution(self, p: TensorLike) -> TensorLike: ...
    

OPCPDEDataT = TypeVar('OPCPDEDataT', bound=OPCPDEDataProtocol)


DATA_TABLE = {
    # example name: (file_name, class_name)
    "opc": ("optimal_control_data_2d", "OptimalControlData2d"),
}


