
api_2023_12 = {
    "__array_api_version__": "2023.12",
    "array object": {
        "operators": {
            },
        "attributes": {
            "dtype": "Data type of the array elements.",
            "device": "Hardware device the array data resides on.",
            "mT": "Transpose of a matrix (or a stack of matrices).",
            "ndim": "Number of array dimensions (axes).",
            "shape": "Array dimensions.",
            "size": "Number of elements in an array.",
            "T": "Transpose of the array.", 
            },
        "methods": {
            "__abs__": None,
            "__add__": None,
            "__and__": None,
            "__array_namespace__": None,
            "__bool__": None,
            "__complex__": None,
            "__dlpack__": None,
            "__dlpack_device__": None,
            "__eq__": None,
            "__float__": None,
            "__floordiv__": None,
            "__ge__": None,
            "__getitem__": None,
            "__gt__": None,
            "__index__": None,
            "__int__": None,
            "__invert__": None,
            "__le__": None,
            "__lshift__": None,
            "__lt__": None,
            "__matmul__": None,
            "__mod__": None,
            "__mul__": None,
            "__ne__": None,
            "__neg__": None,
            "__or__": None,
            "__pos__": None,
            "__pow__": None,
            "__rshift__": None,
            "__setitem__": None,
            "__sub__": None,
            "__truediv__": None,
            "__xor__": None,
            "to_device": None,
            },
        },
    "constants": {
            "e": None,
            "inf": None,
            "nan": None,
            "newaxis": None,
            "pi": None,
        },
    "creation functions": {
            "arange": None,
            "asarray": None,
            "empty": None,
            "empty_like": None,
            "eye": None,
            "from_dlpack": None,
            "full": None,
            "full_like": None,
            "linspace": None,
            "meshgrid": None,
            "ones": None,
            "ones_like": None,
            "tril": None,
            "triu": None,
            "zeros": None,
            "zeros_like": None,
        },
    "data type functions": {
            "astype": None,
            "can_cast": None,
            "finfo": None,
            "iinfo": None,
            "isdtype": None,
            "result_type": None,
        },
    "data types": {
            "bool": None,
            "int8": None,
            "int16": None,
            "int32": None,
            "int64": None,
            "uint8": None,
            "uint16": None,
            "uint32": None,
            "uint64": None,
            "float32": None,
            "float64": None,
            "complex64": None,
            "complex128": None,
            "categories":{
                "numeric": (
                    "int8", "int16", "int32", "int64", "uint8", "uint16", "uint32",
                    "uint64", "float32", "float64", "complex64",  "complex128"
                    ),
                "real-valued": (
                    "int8", "int16", "int32", "int64", "uint8", "uint16", "uint32",
                    "uint64", "float32", "float64"
                    ),
                "integer": (
                    "int8", "int16", "int32", "int64", "uint8", "uint16", "uint32",
                    ),
                "floating-point": (
                    "float32", "float64", "complex64",  "complex128"
                    ),
                "real-valued_floating-point": (
                    "float32", "floa64"
                    ),
                "complex floating-point": (
                    "complex64", "complex128"
                    )
                "boolean": ("bool", ),
                }
        },
    "element-wise functions": {
            "abs": None,
            "acos": None,
            "acosh": None,
            "add": None,
            "asin": None,
            "asinh": None,
            "atan": None,
            "atan2": None,
            "atanh": None,
            "bitwise_and": None,
            "bitwise_left_shift": None,
            "bitwise_invert": None,
            "bitwise_or": None,
            "bitwise_right_shift": None,
            "bitwise_xor": None,
            "ceil": None,
            "clip": None,
            "conj": None,
            "copysign": None,
            "cos": None,
            "cosh": None,
            "divide": None,
            "equal": None,
            "exp": None,
            "expm1": None,
            "floor": None,
            "floor_divide": None,
            "greater": None,
            "greater_equal": None,
            "hypot": None,
            "imag": None,
            "isfinite": None,
            "isinf": None,
            "isnan": None,
            "less": None,
            "less_equal": None,
            "log": None,
            "log1p": None,
            "log2": None,
            "log10": None,
            "logaddexp": None,
            "logical_and": None,
            "logical_not": None,
            "logical_or": None,
            "logical_xor": None,
            "maximum": None,
            "minimum": None,
            "multiply": None,
            "negative": None,
            "not_equal": None,
            "positive": None,
            "pow": None,
            "real": None,
            "remainder": None,
            "round": None,
            "sign": None,
            "signbit": None,
            "sin": None,
            "sinh": None,
            "square": None,
            "sqrt": None,
            "subtract": None,
            "tan": None,
            "tanh": None,
            "trunc": None,
        },
    "indexing functions": {
            "take": None, 
            },
    "manipulation functions": {
            "broadcast_arrays": None,
            "broadcast_to": None,
            "concat": None,
            "expand_dims": None,
            "flip": None,
            "moveaxis": None,
            "permute_dims": None,
            "repeat": None,
            "reshape": None,
            "roll": None,
            "squeeze": None,
            "stack": None,
            "tile": None,
            "unstack": None,
        },
    "searching functions": {
            "argmax": None,
            "argmin": None,
            "nonzero": None,
            "searchsorted": None,
            "where": None,
        },
    "set functions": {
            "unique_all": None,
            "unique_counts": None,
            "unique_inverse": None,
            "unique_values": None,
        },
    "sorting functions": {
            "argsort": None,
            "sort": None,
        },
    "statistical functions":{
            "cumulative_sum": None,
            "max": None,
            "mean": None,
            "min": None,
            "prod": None,
            "std": None,
            "sum": None,
            "var": None,
        },
    "utility functions": {
            "all": None,
            "any": None,
        },
    "random": {

            },
    "linalg": {
        },
    "fft": {
        },
}
