from typing import Protocol, Sequence, TypeVar
from ...backend import TensorLike


class WavePDEDataProtocol(Protocol):
    def geo_dimension(self) -> int: ...
    def domain(self) -> Sequence[float]: ...
    def duration(self) -> Sequence[float]: ...
    def init_solution(self, p: TensorLike) -> TensorLike: ...
    def init_solution_t(self, p: TensorLike) -> TensorLike: ...
    def solution(self, p: TensorLike, t: float) -> TensorLike: ...
    def gradient(self, p: TensorLike, t: float) -> TensorLike: ...
    def source(self, p: TensorLike, t: float) -> TensorLike: ...
    def dirichlet(self, p: TensorLike, t:float) -> TensorLike: ...
    def is_dirichlet_boundary(self, p: TensorLike) -> TensorLike: ...

WavePDEDataT = TypeVar('WavePDEDataT', bound=WavePDEDataProtocol)


DATA_TABLE = {
    # example name: (file_name, class_name)
    "sincos": ("sin_cos_data_2d", "SinCosData2D"),
    "sinmix": ("sin_mix_data_1d", "SinMixData1D")

}
