from typing import Sequence

from fealpy.backend import TensorLike
from fealpy.backend import backend_manager as bm
from fealpy.decorator import cartesian, variantmethod
from fealpy.mesher.circle_mesher import CircleMesher


class Exp0009(CircleMesher):
    """
    2D steady Navier-Stokes manufactured solution on the unit disk.

        -mu Delta u + (u · grad)u + grad p = f  in Omega
        div u = 0                                  in Omega
        u = g                                      on boundary Omega

    Domain:
        Omega = {(x, y): x**2 + y**2 < 1}

    Exact solution:
        a(x, y) = 1 - x**2 - y**2
        u1(x, y) = -4 y a
        u2(x, y) =  4 x a
        p(x, y)  = x**2 - y**2

    The velocity is generated by the stream function psi = (1-r**2)**2,
    so it is exactly divergence-free and vanishes on the circular boundary.
    The pressure has zero mean over the unit disk.
    """

    def __init__(self, option: dict | None = None):
        if option is None:
            option = {}

        self.options = option
        self.box = [-1.0, 1.0, -1.0, 1.0]
        self.radius = 1.0
        self.center = (0.0, 0.0)
        self.eps = float(option.get("eps", 1.0e-10))
        self.mu = bm.tensor(option.get("mu", 1.0))
        self.rho = bm.tensor(option.get("rho", 1.0))
        self.base_h = float(option.get("h", 0.2))
        self.default_mesh_type = "unit_tri"
        self.supports_geometric_refine = True
        super().__init__(h=self.base_h)

    def geo_dimension(self) -> int:
        return 2

    def domain(self) -> Sequence[float]:
        return self.box

    def viscosity(self) -> TensorLike:
        return self.mu

    def _effective_h(self, mesh_refine: int = 0, h: float | None = None) -> float:
        mesh_refine = int(mesh_refine)
        if mesh_refine < 0:
            raise ValueError("mesh_refine must be non-negative.")
        base_h = self.base_h if h is None else float(h)
        return base_h / (2**mesh_refine)

    def _circle_vertices(self, h: float) -> TensorLike:
        n = max(8, int(2 * bm.pi / h))
        theta = bm.linspace(0, 2 * bm.pi, n, endpoint=False)
        return bm.stack([bm.cos(theta), bm.sin(theta)], axis=-1)

    def _generate_mesh(self, mesh_type: str, mesh_refine: int = 0):
        """Regenerate the circular geometry at the requested resolution.

        For this curved-domain benchmark, ``mesh_refine`` means decreasing the
        target mesh size ``h`` and calling the geometry-aware mesher again.  A
        plain ``uniform_refine`` would split the current polygonal boundary and
        would not project new boundary nodes back onto the unit circle.
        """
        old_h = self.h
        old_vertices = self.vertices
        refined_h = self._effective_h(mesh_refine)
        self.h = refined_h
        self.vertices = self._circle_vertices(refined_h)
        try:
            return super().init_mesh[mesh_type]()
        finally:
            self.h = old_h
            self.vertices = old_vertices

    @variantmethod("unit_tri")
    def init_mesh(self, mesh_refine: int = 0):
        return self._generate_mesh("unit_tri", mesh_refine)

    @init_mesh.register("tri")
    def init_mesh(self, mesh_refine: int = 0):
        return self._generate_mesh("tri", mesh_refine)

    @init_mesh.register("quad")
    def init_mesh(self, mesh_refine: int = 0):
        return self._generate_mesh("quad", mesh_refine)

    @staticmethod
    def _a(p: TensorLike) -> TensorLike:
        x, y = p[..., 0], p[..., 1]
        return 1.0 - x * x - y * y

    @cartesian
    def velocity(self, p: TensorLike) -> TensorLike:
        x, y = p[..., 0], p[..., 1]
        a = self._a(p)
        u1 = -4.0 * y * a
        u2 = 4.0 * x * a
        return bm.stack([u1, u2], axis=-1)

    @cartesian
    def velocity_u(self, p: TensorLike) -> TensorLike:
        y = p[..., 1]
        return -4.0 * y * self._a(p)

    @cartesian
    def velocity_v(self, p: TensorLike) -> TensorLike:
        x = p[..., 0]
        return 4.0 * x * self._a(p)

    @cartesian
    def pressure(self, p: TensorLike) -> TensorLike:
        x, y = p[..., 0], p[..., 1]
        return x * x - y * y

    @cartesian
    def grad_velocity(self, p: TensorLike) -> TensorLike:
        x, y = p[..., 0], p[..., 1]
        du1_dx = 8.0 * x * y
        du1_dy = -4.0 + 4.0 * x * x + 12.0 * y * y
        du2_dx = 4.0 - 12.0 * x * x - 4.0 * y * y
        du2_dy = -8.0 * x * y
        return bm.stack([
            bm.stack([du1_dx, du1_dy], axis=-1),
            bm.stack([du2_dx, du2_dy], axis=-1),
        ], axis=-2)

    @cartesian
    def div_velocity(self, p: TensorLike) -> TensorLike:
        x = p[..., 0]
        return bm.zeros_like(x)

    @cartesian
    def grad_pressure(self, p: TensorLike) -> TensorLike:
        x, y = p[..., 0], p[..., 1]
        return bm.stack([2.0 * x, -2.0 * y], axis=-1)

    @cartesian
    def lap_velocity(self, p: TensorLike) -> TensorLike:
        x, y = p[..., 0], p[..., 1]
        lap_u1 = 32.0 * y
        lap_u2 = -32.0 * x
        return bm.stack([lap_u1, lap_u2], axis=-1)

    @cartesian
    def convective(self, p: TensorLike) -> TensorLike:
        x, y = p[..., 0], p[..., 1]
        a = self._a(p)
        factor = -16.0 * a * a
        return bm.stack([factor * x, factor * y], axis=-1)

    @cartesian
    def source(self, p: TensorLike) -> TensorLike:
        return (
            -self.mu * self.lap_velocity(p)
            + self.convective(p)
            + self.grad_pressure(p)
        )

    @cartesian
    def source_u(self, p: TensorLike) -> TensorLike:
        return self.source(p)[..., 0]

    @cartesian
    def source_v(self, p: TensorLike) -> TensorLike:
        return self.source(p)[..., 1]

    @cartesian
    def dirichlet_velocity(self, p: TensorLike) -> TensorLike:
        return self.velocity(p)

    @cartesian
    def dirichlet_velocity_u(self, p: TensorLike) -> TensorLike:
        return self.velocity_u(p)

    @cartesian
    def dirichlet_velocity_v(self, p: TensorLike) -> TensorLike:
        return self.velocity_v(p)

    @cartesian
    def neumann_pressure(self, p: TensorLike) -> TensorLike:
        # On the unit circle n = (x, y), so grad(p) · n = 2(x**2-y**2).
        return 2.0 * self.pressure(p)

    @cartesian
    def neumann_pressure_correct(self, p: TensorLike) -> TensorLike:
        return self.neumann_pressure(p)

    @cartesian
    def dirichlet_pressure(self, p: TensorLike) -> TensorLike:
        return self.pressure(p)

    def pressure_integral_target(self) -> float:
        return 0.0

    @cartesian
    def is_velocity_boundary(self, p: TensorLike) -> TensorLike:
        x, y = p[..., 0], p[..., 1]
        return bm.abs(x * x + y * y - 1.0) < self.eps

    @cartesian
    def is_pressure_boundary(self, p: TensorLike) -> TensorLike:
        x = p[..., 0]
        return bm.zeros_like(x, dtype=bm.bool)

    @cartesian
    def is_neumann_boundary(self, p: TensorLike) -> TensorLike:
        return self.is_velocity_boundary(p)
