from __future__ import annotations

from typing import Sequence

from fealpy.backend import TensorLike
from fealpy.backend import backend_manager as bm
from fealpy.decorator import cartesian
from fealpy.mesher import BoxMesher2d


class Exp0015(BoxMesher2d):
    r"""Steady two-dimensional traction-outlet manufactured solution.

    The velocity is generated by the stream function

    .. math::

        \psi(x,y)=A H(y)+B F(x)k(y),

    while the pressure is chosen so that the right boundary satisfies

    .. math::

        (\mu\nabla u-pI)n=0.
    """

    def __init__(self, option: dict | None = None):
        option = {} if option is None else option
        self.options = option
        self.box = [0.0, 1.0, 0.0, 1.0]
        self.mu = bm.tensor(option.get("mu", 1.0))
        self.rho = bm.tensor(option.get("rho", 1.0))
        self.A = float(option.get("A", 0.25))
        self.B = float(option.get("B", 0.5))
        self.C0 = float(option.get("C0", 0.2))
        self.C1 = float(option.get("C1", 0.1))
        self.eps = float(option.get("eps", 1.0e-12))
        self.default_mesh_type = "uniform_quad"
        super().__init__(box=self.box)

    def geo_dimension(self) -> int:
        return 2

    def domain(self) -> Sequence[float]:
        return self.box

    def viscosity(self) -> TensorLike:
        return self.mu

    def density(self) -> TensorLike:
        return self.rho

    def H(self, y):
        return 3.0 * y**2 - 2.0 * y**3

    def Hp(self, y):
        return 6.0 * y - 6.0 * y**2

    def Hpp(self, y):
        return 6.0 - 12.0 * y

    def Hppp(self, y):
        return -12.0 * bm.ones_like(y)

    def k(self, y):
        return y**2 - 2.0 * y**3 + y**4

    def kp(self, y):
        return 2.0 * y - 6.0 * y**2 + 4.0 * y**3

    def kpp(self, y):
        return 2.0 - 12.0 * y + 12.0 * y**2

    def kppp(self, y):
        return -12.0 + 24.0 * y

    def F(self, x):
        return x**2 - x**3 / 3.0

    def Fp(self, x):
        return 2.0 * x - x**2

    def Fpp(self, x):
        return 2.0 - 2.0 * x

    def Fppp(self, x):
        return -2.0 * bm.ones_like(x)

    def r(self, y):
        return self.C0 + self.C1 * y * (1.0 - y)

    def rp(self, y):
        return self.C1 * (1.0 - 2.0 * y)

    @cartesian
    def velocity(self, points: TensorLike) -> TensorLike:
        x, y = points[..., 0], points[..., 1]
        u = self.A * self.Hp(y) + self.B * self.F(x) * self.kp(y)
        v = -self.B * self.Fp(x) * self.k(y)
        return bm.stack([u, v], axis=-1)

    @cartesian
    def pressure(self, points: TensorLike) -> TensorLike:
        x, y = points[..., 0], points[..., 1]
        return self.mu * self.B * self.kp(y) + (1.0 - x) * self.r(y)

    @cartesian
    def grad_velocity(self, points: TensorLike) -> TensorLike:
        x, y = points[..., 0], points[..., 1]
        u_x = self.B * self.Fp(x) * self.kp(y)
        u_y = self.A * self.Hpp(y) + self.B * self.F(x) * self.kpp(y)
        v_x = -self.B * self.Fpp(x) * self.k(y)
        v_y = -self.B * self.Fp(x) * self.kp(y)
        return bm.stack(
            [
                bm.stack([u_x, u_y], axis=-1),
                bm.stack([v_x, v_y], axis=-1),
            ],
            axis=-2,
        )

    @cartesian
    def div_velocity(self, points: TensorLike) -> TensorLike:
        gradient = self.grad_velocity(points)
        return gradient[..., 0, 0] + gradient[..., 1, 1]

    @cartesian
    def lap_velocity(self, points: TensorLike) -> TensorLike:
        x, y = points[..., 0], points[..., 1]
        lap_u = (
            self.B * self.Fpp(x) * self.kp(y)
            + self.A * self.Hppp(y)
            + self.B * self.F(x) * self.kppp(y)
        )
        lap_v = (
            -self.B * self.Fppp(x) * self.k(y)
            - self.B * self.Fp(x) * self.kpp(y)
        )
        return bm.stack([lap_u, lap_v], axis=-1)

    @cartesian
    def grad_pressure(self, points: TensorLike) -> TensorLike:
        x, y = points[..., 0], points[..., 1]
        pressure_x = -self.r(y)
        pressure_y = self.mu * self.B * self.kpp(y) + (1.0 - x) * self.rp(y)
        return bm.stack([pressure_x, pressure_y], axis=-1)

    @cartesian
    def convective(self, points: TensorLike) -> TensorLike:
        velocity = self.velocity(points)
        gradient = self.grad_velocity(points)
        return (
            velocity[..., 0, None] * gradient[..., :, 0]
            + velocity[..., 1, None] * gradient[..., :, 1]
        )

    @cartesian
    def source(self, points: TensorLike) -> TensorLike:
        return (
            -self.mu * self.lap_velocity(points)
            + self.convective(points)
            + self.grad_pressure(points)
        )

    @cartesian
    def traction(self, points: TensorLike) -> TensorLike:
        gradient = self.grad_velocity(points)
        pressure = self.pressure(points)
        viscous_normal = self.mu * gradient[..., :, 0]
        pressure_normal = bm.stack(
            [pressure, bm.zeros_like(pressure)],
            axis=-1,
        )
        return viscous_normal - pressure_normal

    @cartesian
    def dirichlet_velocity(self, points: TensorLike) -> TensorLike:
        return self.velocity(points)

    @cartesian
    def is_inlet_boundary(self, points: TensorLike) -> TensorLike:
        return bm.abs(points[..., 0]) <= self.eps

    @cartesian
    def is_outlet_boundary(self, points: TensorLike) -> TensorLike:
        return bm.abs(points[..., 0] - 1.0) <= self.eps

    @cartesian
    def is_wall_boundary(self, points: TensorLike) -> TensorLike:
        y = points[..., 1]
        on_wall = (bm.abs(y) <= self.eps) | (bm.abs(y - 1.0) <= self.eps)
        return on_wall & ~(
            self.is_inlet_boundary(points) | self.is_outlet_boundary(points)
        )

    @cartesian
    def is_velocity_boundary(self, points: TensorLike) -> TensorLike:
        return self.is_inlet_boundary(points) | self.is_wall_boundary(points)

    is_dirichlet_boundary = is_velocity_boundary

    def pressure_mean(self) -> float:
        return 0.5 * (self.C0 + self.C1 / 6.0)
