import numpy as np

l_shape_mesher_data = [
    {"big_box": (-1, 1, -1, 1),
     "small_box": (0, 1, 0, 1),
     "nx": 10, "ny": 10,
     "mesh_type": "tri_threshold",
     },
    {"big_box": (-1, 1, -1, 1),
     "small_box": (0, 1, 0, 1),
     "nx": 10, "ny": 10,
     "mesh_type": "quad_threshold",
     },
    {"big_box": (-1, 1, -1, 1),
     "small_box": (0, 1, -1, 0),
     "nx": 10, "ny": 10,
     "mesh_type": "tri_threshold",
     },
    {"big_box": (-1, 1, -1, 1),
     "small_box": (0, 1, -1, 0),
     "nx": 10, "ny": 10,
     "mesh_type": "quad_threshold",
     },
    {"big_box": (-1, 1, -1, 1),
     "small_box": (-1, 0, 0, 1),
     "nx": 10, "ny": 10,
     "mesh_type": "tri_threshold",
     },
    {"big_box": (-1, 1, -1, 1),
     "small_box": (-1, 0, 0, 1),
     "nx": 10, "ny": 10,
     "mesh_type": "quad_threshold",
     },
    {"big_box": (-1, 1, -1, 1),
     "small_box": (-1, 0, -1, 0),
     "nx": 10, "ny": 10,
     "mesh_type": "tri_threshold",
     },
    {"big_box": (-1, 1, -1, 1),
     "small_box": (-1, 0, -1, 0),
     "nx": 10, "ny": 10,
     "mesh_type": "quad_threshold",
     },
]
