from typing import Protocol, Sequence, TypeVar
from ...backend import TensorLike


class DarcyforchheimerDataProtocol(Protocol):
    """Protocol interface for Darcy–Forchheimer PDE data components."""
    def geo_dimension(self) -> int: ...
    def domain(self) -> Sequence[float]: ...
    def pressure(self, p: TensorLike) -> TensorLike: ...
    def velocity(self, p: TensorLike) -> TensorLike: ...
    def grad_pressure(self, p: TensorLike) -> TensorLike: ...
    def source(self, p: TensorLike) -> TensorLike: ...
    def flux(self, p: TensorLike) -> TensorLike: ...
    def neumann(self, p: TensorLike) -> TensorLike: ...

DFDataT = TypeVar('DarcyforchheimerDataT', bound=DarcyforchheimerDataProtocol)

"""
DATA_TABLE is a registry, when adding new PDE models, 
follow the existing examples to register them in the registry.
"""

DATA_TABLE = {
    "sin": ("sin_data_1d", "SinData1D"),
}
