from .lagrange_fem_space import LagrangeFiniteElementSpace
from .mixed_fem_space import RTFiniteElementSpace2d
from .vem_space import VEMDof2d, VirtualElementSpace2d
from .ConformingVirtualElementSpace2d import CVEMDof2d, ConformingVirtualElementSpace2d
from .NonConformingVirtualElementSpace2d import NCVEMDof2d, NonConformingVirtualElementSpace2d
from .ScaledMonomialSpace2d import ScaledMonomialSpace2d
from .MonomialSpace2d import MonomialSpace2d
from .PrismFiniteElementSpace import CPPFEMDof3d
from .QuadBilinearFiniteElementSpace import QuadBilinearFiniteElementSpace
from .surface_lagrange_fem_space import SurfaceLagrangeFiniteElementSpace
