source "https://rubygems.org"

gem "jekyll-text-theme"
gem "jekyll", "~> 3.9" # github-pages needs 3.9.0

group :jekyll_plugins do
    gem "github-pages"
    gem "jekyll-paginate"
    gem "jekyll-sitemap"
    gem "jekyll-include-cache"
    gem "jekyll-feed"
    gem "jemoji"
end
